version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: golearn-upload-db
    environment:
      - POSTGRES_USER=golearn_user
      - POSTGRES_PASSWORD=golearn_password
      - POSTGRES_DB=golearn_db
    ports:
      - "5432:5432"
    volumes:
      - golearn-upload-db:/var/lib/postgresql/data/

volumes:
  golearn-upload-db: {}
